# pyproject.toml
"""
This file is used to configure the project.
"""

[tool.pylint.'MESSAGES CONTROL']
max-line-length = 120

[tool.pylint.'FORMAT']
max-line-length = 120

[tool.pylint.'DESIGN']
max-parents = 10

[tool.pylint.'REPORTS']
output-format = "colorized"
reports = true